<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/25 14:36:36

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
