<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/28 10:35:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
