<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/02 11:28:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet_test',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
